### ISSUE TITLE
Fetch quotes API data

### ISSUE THREAD

**Issue by SimpleLuke** [SimpleLuke/clock-app#2]
Fetch quotes API data

###Tasks:

- [x] Fetch quote and author
- [x] Add random refresher
- [x]  Bonus: update animation
