### ISSUE TITLE
Fetch time API data based on visitor’s IP address

### ISSUE THREAD

**Issue by SimpleLuke** [SimpleLuke/clock-app#3]
Fetch time API data based on visitor’s IP address

###Tasks:

- [x] Fetch Clock time
- [x] Fetch abbreviation
- [x] Update every minute
- [x] Good Morning / Good Evening in condition with icon changes
