### ISSUE TITLE
Create expanding UI

### ISSUE THREAD

**Issue by SimpleLuke** [SimpleLuke/clock-app#5]
Create expanding UI

###Tasks:

- [x] Animate clock up when expanded class is on
- [x] Quote disappear when expanded class is on
- [x] Create Expanding UI
- [x] Fetch Data into the expanding detail
